[package]
name = "Bridge"
version = "0.1.0"

[addresses]
StarcoinFramework="0x1"
Bridge = "0xb6d69dd935edf7f2054acf12eb884df8"

[dependencies]
StarcoinFramework = { git = "https://github.com/starcoinorg/starcoin-framework.git", rev = "01c84198819310620f2417413c3c800df8292ae5" }